[package]
name = "raytracer-rs"
version = "0.1.0"
authors = ["kanales <ivancanalestgna@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.2" 